#! /bin/sh

if [ $# -lt 1 ]; then
    echo "missing package name to uninstall"
    exit 1
fi

for package_dir in "$(uniget root)/packages/${1}"*; do
    if [ "$1" = "$(basename $package_dir | sed 's/\(\.[0-9]*\)*$//')" ]; then
        printf "uninstall $(echo "$1" | sed 's/\./ /')? [y/N] "
        read ans
        case $ans in
            Y|y)
                for shim in "$(uniget root)"/shims/*; do
                    if grep -q "^# from package: $(basename $package_dir)\$" "$shim"; then
                        rm $shim
                        echo "rm $shim"
                    fi
                done

                rm -rf "$package_dir"
                echo "uninstalled $1"
                ;;

            *)
                echo "canceled"
                break
                ;;
        esac
    fi
done

echo "done"

